### ISSUE TITLE
There was a problem using in my ppt.

### ISSUE THREAD

**Issue by LFpretty** [sandraros/PPT-VBA-pseudo-recorder#1]
Hello, thanks tor your sharing. But there are some wrong that i don't know how to solve, can you help me ?
![20211122223754](https://user-images.githubusercontent.com/93117526/142880338-c9557a0c-696b-4e3a-b4fa-cb7a0b32f1cf.png)

**Comment by sandraros** [comment]
Hi, sorry to not have seen your issue (I don't know why I didn't receive an alert). Note that I don't speak Chinese, if possible please provide English. If your issue is not solved, please reopen the issue.
